# MapFree default config
# Override with mx150.yaml for 2GB VRAM hardware

feature_extractor:
  max_image_size: 2000
  gpu_index: 0

matcher:
  type: spatial  # or sequential
  gpu_index: 0

mapper:
  ba_global_max_iterations: 50
  ba_global_max_refinements: 5

image_undistorter:
  # uses pipeline defaults

patch_match_stereo:
  max_image_size: 1600
  gpu_index: 0

system:
  num_threads: 4
